### ISSUE TITLE
MLab HomePod上onnx转TNN报错：ImportError: cannot import name 'optimizer' from 'onnx' (/opt/conda/lib/python3.8/site-packages/onnx/__init__.py)

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#27]
转换命令如下（开启了-optimize=1 开关）：
```bash
python3 onnx2tnn.py /app/gemfield/onnxmodels/v2.onnx -version=v1.0 -optimize=1 -half=0 -o /app/gemfield/onnxmodels
```
然后报错：
```bash
Traceback (most recent call last):
  File "onnx2tnn.py", line 41, in do_optimize
    import onnx2tnn.onnx_optimizer.onnx_optimizer as opt
ModuleNotFoundError: No module named 'onnx2tnn.onnx_optimizer'; 'onnx2tnn' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onnx2tnn.py", line 148, in <module>
    main()
  File "onnx2tnn.py", line 120, in main
    do_optimize(onnx_net_path, input_shape)
  File "onnx2tnn.py", line 43, in do_optimize
    import onnx_optimizer.onnx_optimizer as opt
  File "/app/gemfield/github/TNN/tools/onnx2tnn/onnx-converter/onnx_optimizer/onnx_optimizer.py", line 8, in <module>
    from onnx import optimizer
ImportError: cannot import name 'optimizer' from 'onnx' (/opt/conda/lib/python3.8/site-packages/onnx/__init__.py)
```

**Comment by gemfield** [comment]
这是因为MLab HomePod 1.0及以后安装的onnx版本是1.9.0，这个版本上onnx已经剥离了optimizer模块。一个临时解决方案就是把onnx回退到最近的旧版本：
```bash
pip install onnx==1.8.1
```

TNN推荐的是1.6.0，实际测试1.8.1也ok。
