### ISSUE TITLE
[bug] HomePod上import onnx_coreml出错

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#37]
```bash
>>> import onnx_coreml
WARNING:root:scikit-learn version 0.24.1 is not supported. Minimum required version: 0.17. Maximum required version: 0.19.2. Disabling scikit-learn conversion API.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/onnx_coreml/__init__.py", line 6, in <module>
    from .converter import convert
  File "/opt/conda/lib/python3.8/site-packages/onnx_coreml/converter.py", line 35, in <module>
    from coremltools.converters.nnssa.coreml.graph_pass.mlmodel_passes import remove_disconnected_layers, transform_conv_crop
```
有人遇到过这个问题了：https://github.com/onnx/onnx-coreml/issues/585

**Comment by gemfield** [comment]
MLab HomePod 1.1 内置的coremltools 为4.1版本，4.0版本后，coremltools不需要经过onnx，直接从pytorch转换为coreml模型：
```bash
import coremltools
# Convert to Core ML using the Unified Conversion API
model = coremltools.convert(
    traced_model,
    inputs=[coremltools.ImageType(name="input", shape=example_input.shape)], 
    classifier_config = coremltools.ClassifierConfig(class_labels) # 可选
)

# Set feature descriptions (these show up as comments in XCode)
model.input_description["input_1"] = "Input image to be classified"
model.output_description["classLabel"] = "Most likely image category"

# Set model author name
model.author = '"DeepVAC'

# Set the license of the model
model.license = "GPLv3"

model.short_description = "Powered by DeepVAC"

# Set a version for the model
model.version = "1.0"
```
