### ISSUE TITLE
tensorrt runtime has depency on pycuda

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#42]
Install pycuda with:
```bash
pip3 install pycuda
```

**Comment by gemfield** [comment]
pycuda包将内置在homepod:2.0 pro版本中，标准版不支持是因为缺少cuda开发环境。

**Comment by gemfield** [comment]
使用命令：
```bash
pip3 install 'pycuda<2021.1'
```
否则会报错：
```bash
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9y4nl9bn/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'numpy; python_version >= '"'"'3.10'"'"'' 'numpy==1.19.5; python_version >= '"'"'3.8'"'"' and python_version < '"'"'3.10'"'"'' 'numpy==1.15.4; python_version >= '"'"'3.7'"'"' and python_version < '"'"'3.8'"'"'' 'numpy==1.12.1; python_version < '"'"'3.7'"'"''
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/conda/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/opt/conda/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/opt/conda/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/opt/conda/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/opt/conda/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/opt/conda/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/opt/conda/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/opt/conda/lib/python3.8/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/opt/conda/lib/python3.8/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9y4nl9bn/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'numpy; python_version >= '"'"'3.10'"'"'' 'numpy==1.19.5; python_version >= '"'"'3.8'"'"' and python_version < '"'"'3.10'"'"'' 'numpy==1.15.4; python_version >= '"'"'3.7'"'"' and python_version < '"'"'3.8'"'"'' 'numpy==1.12.1; python_version < '"'"'3.7'"'"'' Check the logs for full command output.
```
