### ISSUE TITLE
undefined symbol: _ZN3c106ivalue6Future15extractDataPtrsERKNS_6IValueE

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#52]
在MLab HomePod 2.0 pro上使用：
```python
from torchtext.datasets import AG_NEWS
```
报错：
```bash
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from torchtext.datasets import AG_NEWS
  File "/opt/conda/lib/python3.8/site-packages/torchtext/__init__.py", line 5, in <module>
    from . import vocab
  File "/opt/conda/lib/python3.8/site-packages/torchtext/vocab.py", line 13, in <module>
    from torchtext._torchtext import (
ImportError: /opt/conda/lib/python3.8/site-packages/torchtext/_torchtext.so: undefined symbol: _ZN3c106ivalue6Future15extractDataPtrsERKNS_6IValueE
```

**Comment by gemfield** [comment]
这是因为当前环境设置了```PYTHONPATH=/opt/gemfield```，导致程序里使用的是gemfield版pytorch和官方版torchtext，而这两个版本符号不兼容。通过```unset PYTHONPATH``` 让程序使用官方版pytorch来解决该问题。
