### ISSUE TITLE
RuntimeError: cuda runtime error (710) : device-side assert triggered at ......

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#56]
环境：MLab HomePod 2.0 pro
错误：在调用backward() API的时候，PyTorch程序报错，错误栈如下：
```python
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/THC/generic/THCTensorMath.cu line=29 error=710 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    train()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 671, in __call__
    self.process()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 664, in process
    self.train()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 619, in train
    self.doBackward()
  File "train.py", line 26, in doBackward
    super(TransformerTrain, self).doBackward()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 509, in doBackward
    self.config.loss.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuda runtime error (710) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/THC/generic/THCTensorMath.cu:29
```

**Comment by gemfield** [comment]
把设备从cuda换成cpu后，错误信息变为：
```bash
--------------------------------------------
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    train()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 671, in __call__
    self.process()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 664, in process
    self.train()
  File "/opt/gemfield/deepvac/deepvac/core/deepvac.py", line 617, in train
    self.doForward()
  File "train.py", line 22, in doForward
    output = self.config.net(self.config.sample, self.src_mask)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gemfield/hostpv/github/transformer/modules/model_transformer_encoder.py", line 45, in forward
    x = self.encoder(src)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

**Comment by gemfield** [comment]
原因是nn.Embedding(ntoken, emb_size) 前向的时候，输入的索引超过了构造时的ntoken的数量导致的。
