### ISSUE TITLE
OSError: [E050] Can't find model 'de_core_news_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#57]
环境：MLab HomePod 2.0 pro
错误：
```bash
root@homepod:~# python demo.py 
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    token_transform[SRC_LANGUAGE] = get_tokenizer('spacy', language='de_core_news_sm')
  File "/opt/conda/lib/python3.8/site-packages/torchtext/data/utils.py", line 115, in get_tokenizer
    spacy = spacy.load(language)
  File "/opt/conda/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/opt/conda/lib/python3.8/site-packages/spacy/util.py", line 331, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'de_core_news_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
```

**Comment by gemfield** [comment]
解决方案：下载相应的包。
```
python -m spacy download en_core_web_sm
python -m spacy download de_core_news_sm
```
