### ISSUE TITLE
跑PyTorch transformer demo的时候报错：ModuleNotFoundError: No module named 'spacy'

### ISSUE THREAD

**Issue by gemfield** [DeepVAC/MLab#58]
环境: MLab HomePod pro
错误信息：
```bash
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    token_transform[SRC_LANGUAGE] = get_tokenizer('spacy', language='de_core_news_sm')
  File "/opt/conda/lib/python3.8/site-packages/torchtext/data/utils.py", line 113, in get_tokenizer
    import spacy
ModuleNotFoundError: No module named 'spacy'
```

**Comment by gemfield** [comment]
解决方案：
```bash
pip install -U spacy
```
